
#################################
# iRODS iCAT server
sql:
    image: postgres
    volumes:
        - ./confs/pgs_init.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh
    environment:
        POSTGRES_USER: irods
        POSTGRES_PASSWORD: icatserver
        POSTGRES_DB: ICAT

# This image let you access the postgres db with a 'phpmyadmin' like web page
sqladmin:
    image: clue/adminer
    links:
        - sql:db
    ports:
        - 8080:80

#################################
# iRODS iCAT server
icat:
    image: cineca/irods
    hostname: rodserver
    command: sleep 1234567890
    links:
        - sql:db

#################################
# The END
