
#################################
# Data volumes

# EXPECTING:
# $ docker volume ls
# DRIVER              VOLUME NAME
# local               sqldata
# local               irodsdata

# To CREATE THEM the first time:
# $ docker volume create --name sqldata
# $ docker volume create --name irodsdata

#################################
# Postgres database server
sql:
    image: postgres
    volumes:
        - sqldata:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: irods
        POSTGRES_PASSWORD: icatserver
        POSTGRES_DB: ICAT

#################################
# iRODS iCAT server
icat:
    image: cineca/icat
    hostname: rodserver
    # volumes:
    #     # - irodsconf:/etc/irods
    #     # - irodsdata:/home/irods
    #     - ./confs/expect_irods.sh:/tmp/expect
    working_dir: /home/irods
    command: sleep 1234567890
    links:
        - sql:db

#################################
