########################
# took inspiration from:
#https://github.com/irods/contrib/blob/master/irods-docker/icat/Dockerfile

#################################
# Postgres database server
sql:
    image: postgres
    volumes:
        - sqldata:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: irods
        POSTGRES_PASSWORD: icatserver
        POSTGRES_DB: ICAT

#################################
# iRODS iCAT server for EUDAT B2safe
icat:

    # # Simple irods server
    # image: cineca/icat

    ## OR

    # B2safe instance on irods
    image: cineca/b2safe

    hostname: rodserver
    volumes:
        - irodsconf:/etc/irods
        - irodshome:/home/irods
        - irodsresc:/opt/irods_res
        - eudathome:/opt/eudat
    links:
        - sql:db

#################################

# $ docker-compose -f docker-compose.yml -f init.yml up -d
## wait the operations and then press CTRL-c
# $ docker-compose up
