
# inspiration from:
#https://github.com/irods/contrib/blob/master/irods-docker/icat/Dockerfile

#################################
# Postgres database server
sql:
    image: postgres
    volumes:
        - sqldata:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: irods
        POSTGRES_PASSWORD: icatserver
        POSTGRES_DB: ICAT

#################################
# iRODS iCAT server
icat:
    image: cineca/icat
    hostname: rodserver
    volumes:
        - irodsconf:/etc/irods
        - irodshome:/home/irods
        - ./boot.sh:/bootstrap
    working_dir: /home/irods
    command: /bootstrap
    links:
        - sql:db

#################################

# docker-compose -f docker-compose.yml -f init.yml up -d
# docker logs -f irods_icat_1
# docker-compose up

# TO DO:

# 0. extract from deb /etc files
# 1. remove expect and use stdin redirection
# 2. a script to boot irods (second run)
# 3. check resource server
# 4. modify README (init and volume listing)
