########################
# took inspiration from:
#https://github.com/irods/contrib/blob/master/irods-docker/icat/Dockerfile

#################################
# Postgres database server
sql:
    image: postgres
    volumes:
        - sqldata:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: irods
        POSTGRES_PASSWORD: icatserver
        POSTGRES_DB: ICAT

#################################
# iRODS iCAT server
icat:
    #image: cineca/icat
    image: cineca/b2safe
    hostname: rodserver
    #command: sleep infinity
    volumes:
        - irodsconf:/etc/irods
        - irodshome:/home/irods
        - eudathome:/opt/eudat
        - irodsresc:/opt/irods_res
    links:
        - sql:db

#################################

# $ docker-compose -f docker-compose.yml -f init.yml up -d
## wait the operations and then press CTRL-c
# $ docker-compose up
