
#################################
# Data containers from common
sqldata:
  extends:
    file: common.yml
    service: sqldata
irodsdata:
  extends:
    file: common.yml
    service: sqldata

#################################
# Postgres database server
sql:
    image: postgres
    volumes:
        - ./confs/pgs_init.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh
    environment:
        POSTGRES_USER: irods
        POSTGRES_PASSWORD: icatserver
        POSTGRES_DB: ICAT

#################################
# iRODS iCAT server
icat:
    image: cineca/icat
    hostname: rodserver
    command: sleep 1234567890
    links:
        - sql:db

#################################
# The END
